### PR TITLE
use executables on PATH

### PR DESCRIPTION
**Pull request by zimbatm**
Those tools don't always exist in the same locations. For example in
NixOS bash is located under /run/current-system/sw/bin/bash.

### CODE REVIEW

**Comment by Maryse47** [comment]
I always wonder why nix can't just use compat symlinks rather than trying to adjust every single script in universe.

**Comment by zimbatm** [comment]
It's not to be extra annoying if that's what you were wondering :)

I don't know exactly, probably because it's been like that for a long time. It also goes well with the spirit of trying to capture all build and runtime dependencies in all programs. Once programs have all their dependencies on PATH is allows to nicely compose them together as well. For example for this project I have a shell.nix file that declares that OSX-KVM depends on bash, python and qemu and I can control exactly which version is going to be used.

**Comment by kholia** [comment]
Thank you!

The changes look sane and shouldn't break anything. I will merge this in the next batch update.

**Comment by Mic92** [comment]
Works great on my machine!

**Pull request merged**
