### PR TITLE
Add rough notes for developing on the virtualized machine

### PR DESCRIPTION
**Pull request by ADawesomeguy**
Added rough notes for developing on the virtualized OSX machine using prior development knowledge using a MacBook and other notes within this repository for things like USB passthrough.

If something doesn't look right, please let me know what is wrong. This is one of my first few PRs, so if I did something wrong, please point me in the right direction.

### CODE REVIEW

**Comment by kholia** [comment]
Thank you! - this is a good start.

I gave away two of my iPhones and don't have one now to test this stuff - heh!

Are you able to test https://www.net-usb.com/ (`USB Network Gate` stuff) with an iPhone? I suspect that a lot of folks work from laptops and might not be able to do USB controller passthroughs easily (? - not sure).

**Comment by ADawesomeguy** [comment]
Wow, thanks for the quick response! I can definitely give [https://www.net-usb.com/](https://www.net-usb.com/) a shot. You're right about passing through a whole controller - I was trying to figure out another way to do USB passthrough but unfortunately I ran into issues when trying to pass through just one device. I'll take a look and get back to this as soon as I can.

**Comment by kholia** [comment]
I tried this approach a while back. The iPhone (5S?) would keep resetting (rebooting) when I tried to access it via the iTunes running in the OSX VM.

You can try launching iTunes and try to do that "Sync thing" there.

**Comment by ADawesomeguy** [comment]
Interesting. In Catalina and above, iTunes has been replaced by Finder. The issue I'm running into currently is that my iPhone  is showing up in the device tree (intermittently) but not in Finder. It seems that USB over network may be the way to go, but I'm going to try testing passthrough in Catalina because the Big Sur beta, which I am currently testing, is giving me these issues. Hopefully the OS swap will give me some clues as to what I need to do to get it working flawlessly.

**Comment by kholia** [comment]
This `USB over network` approach is not without problems. According to the authors of such software, Apple keeps breaking support for this USB-network functionality pretty often.

I remember folks mentioning that `USB Network Gate` works for them in Catalina.

**Comment by ADawesomeguy** [comment]
I've tested single USB passthrough`with an iPhone, and after much testing and research, it seems that it is not possible in this situation. I'll try a few different USB over network softwares and update this post as soon as I can.

**Comment by kholia** [comment]
> I'll try a few different USB over network software and update this post as soon as I can.

Thanks :+1:

**Comment by ADawesomeguy** [comment]
So far, from what I've seen, USB Network Gate is available in EXE only, and I only have a Linux PC and a Mac laptop. I'll take a deeper look and also test some alternatives that I've seen.

**Comment by kholia** [comment]
It (that program) might also work inside a VirtualBox VM running on Linux.

**Comment by aurelien-m** [comment]
Hello, I'm very interested in being able to work this way. The [USB Network Gate](https://www.net-usb.com/downloads/) app has a trial period and is unfortunately a paid service after that. Do you guys know some alternatives? I've seen [USB/IP](http://usbip.sourceforge.net/) but it's only for Windows and Linux and it's old.

I've also tried connecting my iOS device through USB but it just keeps crashing my VM. I'm trying to build some AR apps so I need the device connected. I will keep looking and update you if I find a way. I'm not super advanced in OpenCore and in Linux VMs in general so I will try my best :)

**Comment by aurelien-m** [comment]
So I found out that you can now build apps for devices connected on your local network with xcode (although you need to have had at least a first usb connection). It works for me now, I was able to connect my iPad to the VM with [this app](https://www.eltima.com/products/usb-over-ethernet/download/) by having the iPad connected to another laptop that I have in my house. It can probably be useful someone else too. I'm not sure how this trial works because you don't have to log in but once you have it setup up with xcode, you can switch it to a local network connection and it's ready for your apps!

**Comment by ADawesomeguy** [comment]
Wow, that's awesome! I'll give it a shot and modify the pull request accordingly. I didn't realize that the software could be used like that because I'm stupid. I appreciate the info!

**Comment by ADawesomeguy** [comment]
Update: I tested out the USB Network Gate software and it worked great for me! I installed the Debian ArmV7 version on my Raspberry Pi and installed the macOS version on the VM, and it was instantly recognized. It's a shame that this is a paid software, especially so expensive. I will look into alternatives, and I have tested out a few things, all of which failed:
- [x] USB Passthrough
- [x] USBIP
- [x] VirtualHere (has only partial support for macOS Mojave and absolutely none for Catalina and Big Sur 😢)
I haven't actually tested VirtualHere, but if it doesn't support it, there's nothing I can do unfortunately. I will do some more research to find something. Hopefully, there's something on GitHub somewhere. I'll add this to the PR and keep looking for solutions!

**Comment by kholia** [comment]
Thank you!

https://github.com/kholia/OSX-KVM/blob/master/Xcode-Tutorial.md is up now.

**Pull request closed without merging**
