### PR TITLE
add non-interactive --version flag

### PR DESCRIPTION
**Pull request by hoshsadiq**
Added a `--version` flag to `fetch-macOS.py` that automatically downloads the requested version or bails if it doesn't exist. This bypasses the user input. This is useful for automation. Backwards compatibility is maintained (i.e. it still asks for user input when not providing the `--version` flag). In addition, a `latest` option can be passed in to automatically determine and download the latest version.

In addition, this also choose curl over wget, as curl often is more reliable in terms of the options that exist. For example, in my case, wget didn't have the option `-x`.

### CODE REVIEW

**Comment by kholia** [comment]
Please no `curl`. Its resume feature is pretty weird and seems to be buggy. In contrast, `wget` works fine as always.

**Comment by hoshsadiq** [comment]
Okay, I think I'm overthinking the curl/wget thing anyway. I realised after I updated this PR that I can install a better version of wget which has the relevant flags. I've removed that commit now.

**Comment by kholia** [comment]
Thanks. I want to use `curl` as it seems to be well maintained but I just couldn't get its resume-download feature to work / work reliably (`wget -c` just works).

**Comment by hoshsadiq** [comment]
Yeah no problem! Let me know if there's anything else you'd like me to change. If not, I think it's ready for merging.

**Comment by kholia** [comment]
I will test + merge this with the next batch update. Thanks :+1:

**Pull request merged**
