### PR TITLE
No sound in Catalina - VoodooHDA missing

### PR DESCRIPTION
**Pull request by jpmorrison**
No sound/microphone using the new OpenCore on Catalina so I put back VoodooHDA

Tested with Catalina / Spice remote viewer

```
-audiodev id=audio1,driver=spice
-device ich9-intel-hda
-device hda-duplex,audiodev=audio1
```

### CODE REVIEW

**Comment by kholia** [comment]
Does this driver work with Big Sur and Monterey?

**Comment by kholia** [comment]
I have updated the https://github.com/kholia/OSX-KVM/blob/master/notes.md#virtual-sound-device section now.

**Comment by sickcodes** [comment]
This was affecting us too, thanks for the PR @jpmorrison!

**Comment by jpmorrison** [comment]
> Does this driver work with Big Sur and Monterey?

I haven't tested it with newer. I want to finish documenting Catalina but I can't figure out how you got the mouse working seamlessly/without grabbing focus.

**Comment by jpmorrison** [comment]
> This was affecting us too, thanks for the PR @jpmorrison!
Thanks - you got me started down this rabbithole!

Are you still on Discord? The invite is expired.

**Comment by jpmorrison** [comment]
> Does this driver work with Big Sur and Monterey?

No sound in Big Sur with or without Voodoo. Tried ich9 and ich6. Need to try with  csrutil disable

**Comment by hzhangxyz** [comment]
should I reinstall the whole system? I use your update, and add
```
-audiodev id=audio1,driver=spice
-device ich9-intel-hda
-device hda-duplex,audiodev=audio1
```
but the system still have no sound device

test in Monterey

**Comment by jpmorrison** [comment]
> should I reinstall the whole system? I use your update, and add
> 
> ```
> -audiodev id=audio1,driver=spice
> -device ich9-intel-hda
> -device hda-duplex,audiodev=audio1
> ```
> 
> but the system still have no sound device
> 
> test in Monterey
I don't know - it worked in Catalina but not Big Sur.

It will probably work if you follow the Hackintosh (VoodooHDA) directions - my guess is boot into recovery so you can run csrutil etc.

This isn't a real fix for out of the box virtualization though. I don't know enough about OpenCore or whether it can fix this at boot time some other way.

Ideally this would be fixed in Qemu by properly emulating Apple sound hardware - maybe it's just vendor IDs.
Big Sur has a virtio-sound driver but Qemu doesn't support this yet.

**Comment by kholia** [comment]
> It will probably work if you follow the Hackintosh (VoodooHDA) directions - my guess is boot into recovery so you can run csrutil etc.

@jpmorrison See https://github.com/chris1111/VoodooHDA-OC. It says `For now the kext not working injected from bootloader on BS 11.3 and later`.

This forces us to remove `VoodooHDA` driver from the OpenCore.qcow2 file, and search for alternate ways to get sound.

**Comment by jpmorrison** [comment]
> > It will probably work if you follow the Hackintosh (VoodooHDA) directions - my guess is boot into recovery so you can run csrutil etc.
> 
> @jpmorrison See https://github.com/chris1111/VoodooHDA-OC. It says `For now the kext not working injected from bootloader on BS 11.3 and later`.
> 
> This forces us to remove `VoodooHDA` driver from the OpenCore.qcow2 file, and search for alternate ways to get sound.

But removing VoodooHDA breaks Catalina sound with Qemu intel-hda. I don't get any sound in Big Sur - is AppleALC supposed to work? It's not working in the quickemu installer. 

Longer term Big Sur and newer has Apple virtio-sound built in. Qemu doesn't implement this yet though. Qemu has usb-audio but it wasn't recognised when I tried it.

**Comment by kholia** [comment]
@jpmorrison 

I recommend opening a PR to add the `--enable-catalina-sound` option to the `opencore-image-ng.sh` script, and also add the corresponding documentation to `notes.md` file.

This will allow folks to get sound in <= macOS Catalina on their own easily. For macOS >= Big Sur, I recommend forward-porting the `virtio-sound` QEMU patches to latest QEMU, and providing binary packages (+ source as always) to end-users.

Does this make sense?

At this point in time, supporting Big Sur + Monterey reliably is required.

**Comment by sickcodes** [comment]
I might add that command line option, some of this commit is perfect, another option is two plists. Im asking users that showed the same error when and which version it happened so I can either put logic in the makefile or the fish script

**Comment by jpmorrison** [comment]
- I forgot that Catalina also has AppleVirtIOAudio 
- FWIW here's the [Qemu virtio-snd patch](https://patchwork.kernel.org/project/qemu-devel/patch/20210429120445.694420-2-chouhan.shreyansh2702@gmail.com/) needs work - in case anyone wants to add to their qemu build @flexiondotorg

**Comment by kholia** [comment]
Please open a new PR when ready.

**Comment by sickcodes** [comment]
Werking on this: https://github.com/sickcodes/osx-serial-generator/commit/d0499f448e9e93c9b1e050cf9246d3c71c747ab6

Will update shortly

**Comment by ETERNALBLUEbullrun** [comment]
Cool, can you use this through `iSH` or `Qemu` (iOS) to produce programs with sound?
https://github.com/ish-app/ish/discussions/2391

**Pull request closed without merging**
