### PR TITLE
AudioDxe introduced since Clover-v2.4k-4844-X64.iso hangs on boot

### PR DESCRIPTION
**Pull request by meeuw**
AudioDxe introduced since Clover-v2.4k-4844-X64.iso hangs on boot

### CODE REVIEW

**Comment by kholia** [comment]
Thank you! I was wondering why the new Clover versions were not booting.

- What do we lose when this file is removed?

- Can you please remove the changes to OVMF_VARS-1024x768.fd in this PR? Squash your commits and force-push please.

**Comment by kholia** [comment]
I was also wondering how hard would it be to maintain a fork of Clover? Must resist...

**Comment by meeuw** [comment]
Whoops, missed that one thanks!

It seems audiodxe is used by clover for playing audio. Removing `-device ich9-intel-hda -device hda-duplex` works as well but then you don't have audio ;-)

I'm working on a test case for a clover bug report.

**Comment by kholia** [comment]
Should we merge this or wait for the upstream Clover project to workaround/fix the problem?

**Comment by kholia** [comment]
```
commit 41c272567cae402b4d7b0084eb7c8f81c8c770da
Author: slice2009 <slice2009@52d7a1c0-eba5-4e63-a9d7-e3186cd7c462>
Date:   Sat Jan 5 08:41:55 2019 +0000

    add AudioDxe driver
    
    git-svn-id: https://svn.code.sf.net/p/cloverefiboot/code@4835 52d7a1c0-eba5-4e63-a9d7-e3186cd7c462
```

AudioDxe seems like a pretty recent addition to Clover. It should be safe to disable it for now.

Thanks!

**Comment by meeuw** [comment]
Yes, OSX-KVM is exactly using Clover 4843 (https://github.com/kholia/OSX-KVM/blame/c36d17c55ad09b14b4270031192fb29513ac88cd/HighSierra/README.md#L99) before audiodxe was introduced (Clover 4844).

I think it is ready to merge, not sure if this is a clover or qemu bug.

**Comment by kholia** [comment]
I am merging this now. Thanks!

I will later push more updates and call the single commit `Batch update for May, 2019`.

**Comment by kholia** [comment]
@meeuw I am wondering how you figured out that this AudioDex stuff was causing problems? I am always eager to learn new debugging approaches :-)

**Comment by meeuw** [comment]
Well, after searching for too long (... really) I found the changelog and I checked what changed by comparing the iso files. Only audiodex seems to be added and I checked if it fixed booting if I removed it.

**Comment by kholia** [comment]
Yep, it's really hard to find that changelog. It is probably the reason why I included that URL in this repository :)

Thanks!

**Pull request merged**
