### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by chuckremes**
The closed issues have answers to a lot of common problems encountered during installation. Plus I discovered a few new problems (and solutions) on my own while working on this. 

So, I improved the documentation a bit by clarifying the exact steps needed to successfully install OSX. Further, I added some more notes on screen resolution. The "LanguageChooser" problem is also pretty common in my experience so I improved the debugging documentation for working around that issue.

Lastly, I have all of this running on newer software releases including Ubuntu 16.10 and QEMU 2.6.1 so I updated the docs to reflect that. Maybe I'll test against QEMU 2.8 too to see if it works.

### CODE REVIEW

**Comment by kholia** [comment]
Thanks, I will try to merge these changes soon.

**Comment by kholia** [comment]
Hi Chuck,

I have manually pulled in your changes. Also, I have combined your changes with mine. Hopefully, the final result looks fine.

**Comment by chuckremes** [comment]
I think a couple of important things got dropped in the merge. Two things in particular.

1. It isn't clear from the current document that there are TWO ways to boot the installation disc. The boot scripts are one way and the `virsh` method is completely different. This was very confusing to me the first time I tried to install. The way it is written now it seems like you need to use the boot scripts AND virsh.

2. The "LanguageChooser" work around using ctrl-F2 did NOT work for me. The super-T method worked 100% of the time. Also, running `diskutil list` is important to identify the correct attached disk. It isn't always disk0 or disk1; on my system it was disk2.

Anyway, please take another look and maybe merge a few more of those changes.

Otherwise, it looks great.

**Comment by kholia** [comment]
Thanks for the feedback. I have merged the `Super-T` method in the README.md. Also, README.md now says,

```
To install OS X, you can use the included `boot.sh` / `boot-macOS.sh` scripts
for a more solid alternate to the following `virsh` method. Use either the
`boot*.sh` method or the following `virsh` method to install OS X / macOS.
```

Hopefully, this text will remove any confusion (1).

**Pull request closed without merging**
