### PR TITLE
WIP: automate the macOS installation

### PR DESCRIPTION
**Pull request by zimbatm**
Status: currently not working completely. The framework is in place. Looking for early feedback to see if that would be interesting to share.

Use qemu in VNC server mode and then use vncdotool to drive the
installation.

The goal is to have a booted, snapshotted VM that can easily be resumed
to get fast startup times. qemu takes ~1s to boot a snapshotted Ubuntu
VMs. If that also works for macOS is means that we can spawn on-demand
VMs quickly and have a fresh install to run automated tests for example.

Usage:

start ./install-macOS-NG.sh in one terminal
start ./automation.sh in another
follow the instructions

once installed, start ./boot-macOS-NG.sh to start the VM without the
install media.

Howto:

The current steps in ./automation.sh have been painstakingly recorded manually and tested multiple times. Small variances in CPU speed can affect the outcome of some of these steps.

TODO:
* actually detect the screens, vncdotools's expect seems to be broken
* actually create a resumable snapshot of the booted VM
* for some reason the installer now fails on reboot. See cap8-error.png
* currently the output image is fairly large (20GB). Is there any way to
  reduce that to a reasonable size?

At some point I want to automate all of the installation process with
Nix as the driver for the build.

### CODE REVIEW

**Comment by Mic92** [comment]
Here is also some NixOS configuration I use to set the kvm configuration: https://github.com/Mic92/dotfiles/blob/master/nixos/modules/macos-kvm.nix

**Comment by kholia** [comment]
> actually create a resumable snapshot of the booted VM.

Thanks - I will work on this idea soon.

**Comment by kholia** [comment]
This is a pretty cool and complex approach.

IMO, we can also install macOS manually in a VM (like usual) one single time and then create a "golden image" (to bootstrap other VMs) quite easily.

I will work on this alternate approach.

Thanks again! :)

**Comment by Mic92** [comment]
I create a wiki article for NixOS as well now: https://nixos.wiki/wiki/OSX-KVM

**Pull request closed without merging**
