### PR TITLE
Avoid deprecated egrep(1)

### PR DESCRIPTION
**Pull request by kdkasad**
Instead of using egrep(1), which is deprecated, use grep(1) with the
'-e' option specified twice.

### CODE REVIEW

**Comment by sickcodes** [comment]
LGTM!

**Comment by speculatrix** [comment]
if you use ShellCheck,m which I highly recommend, then it complains about egrep like this:

```$ shellcheck  shellcheck_egrep_e.sh

In shellcheck_egrep_e.sh line 3:
egrep "1" /etc/hosts
^---^ SC2196: egrep is non-standard and deprecated. Use grep -E instead.

For more information:
  https://www.shellcheck.net/wiki/SC2196 -- egrep is non-standard and depreca...
```

**Comment by speculatrix** [comment]
shellcheck command is available in the ShellCheck package in Fedora, or source is at https://github.com/koalaman/shellcheck

**Comment by pmetzger** [comment]
I hate Shellcheck. It complains about perfectly reasonable and perfectly portable constructs. I suggest not using it. I've seen nice well structured shell scripts ruined in an attempt to appease it. The authors have a very weird idea about what is and isn't reasonable scripting practice.

**Comment by speculatrix** [comment]
I do use shellcheck: disable rather than make a messy appeasement.

**Comment by sickcodes** [comment]
> I hate Shellcheck. It complains about perfectly reasonable and perfectly portable constructs. I suggest not using it. I've seen nice well structured shell scripts ruined in an attempt to appease it. The authors have a very weird idea about what is and isn't reasonable scripting practice.

Shellcheck is very accurate, most of the time it's trying to protect you from command injection. egrep is deprecated but it's still available in almost every repo, as a grep alias.

**Comment by kholia** [comment]
I have merged the `grep -e vmx -e svm /proc/cpuinfo` change manually - thanks!

**Pull request closed without merging**
