### PR TITLE
Severe improvements for OpenCore-Boot

### PR DESCRIPTION
**Pull request by LeanderKlinger**
The two added lines improved my Hackintosh significently, like to the point where it doesn't feel all that non-native. The first one explicitly adds kvm as the acceleration to be used (idk if it truly does that much on it's own) and the second one is using the display gtk instead of sdl, which lessens cpu strain immensely

### CODE REVIEW

**Comment by Ashtonian** [comment]
do you know what these are in xml terms?

**Comment by scorpio810** [comment]
I use 
```
cat OpenCore-Boot.sh
 -monitor stdio
  -device qxl-vga
)
```
```
cat OpenCore-Boot-macOS.sh 
  -monitor stdio
  -device qxl-vga
  -accel kvm
  -display gtk
)
```

**Comment by ChGen** [comment]
Agree, both arguments improve perceived performance. As for me, ` -accel kvm` didn't work, so I use ` -machine q35,accel=kvm` instead.

**Comment by ChGen** [comment]
But macOS installation process is unstable with this KVM option on....

**Pull request closed without merging**
