### PR TITLE
switch back to downloading to URI path segment

### PR DESCRIPTION
**Pull request by redradrat**
Just switched back the comments to produce the required URI path based structure... :)

### CODE REVIEW

**Comment by kholia** [comment]
We now want the downloaded file to land in the current folder and not in a nested path (which you patch seems to be doing?).

**Comment by jchv** [comment]
It seems that the script, at least in the state its in in master, is still looking for the nested paths. Are you sure you don't still have the nested paths locally, making it look like it's working?

FWIW, I got the script working doing something similar to this patch.

**Comment by kholia** [comment]
I have tested the script end-to-end and it seems to be working well.

**Comment by DonnieWest** [comment]
On current master, I also received the following error from a fresh clone:

```
./fetch-macOS.py:205: DeprecationWarning: The readPlist function is deprecated, use load() instead
  catalog = plistlib.readPlist(localcatalogpath)
Error reading content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: [Errno 2] No such file or directory: 'content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog'
```

Using this patch fixed the issue. I also noticed that running the patched code, reverting, and then running again caused everything to work as well. `.gitgnore` is set for `*.sucatalog` so that might make things look like there's no dfiference when there really is :)

**Comment by kholia** [comment]
This patch cannot fix those API deprecation problems. See the man page of wget to see what this patch does.

Note: We need to support Python 2.x and Python 3 at the same time.

**Comment by DonnieWest** [comment]
Sorry, the deprecation warning shouldn't have been included - the rest of what I said is still relevant despite that though

**Comment by kholia** [comment]
I was on mobile earlier. Yes, I see the problem now. Thanks for the patch!

**Comment by kholia** [comment]
@DonnieWest Great debugging catch :+1:  Thank you.

**Pull request merged**
