### PR TITLE
non-APFS not possible for newer OSX

### PR DESCRIPTION
**Pull request by gotjoshua**

### CODE REVIEW

**Comment by kkremitzki** [comment]
Typo: `Mohave` should be `Mojave`

**Comment by kholia** [comment]
Non-APFS filesystems work just fine on Ventura and other versions.

**Comment by gotjoshua** [comment]
> work just fine

really!?! how to convince the installer to choose a non apfs drive?  do you have links to instructions?

image

**Comment by kholia** [comment]
Just use the `Disk Utility` to format the disk with non-APFS. No special or out of the way steps are involved.

Screenshot_2023-12-29_16-10-47
Screenshot_2023-12-29_21-04-12

**Comment by thenickdude** [comment]
What? But the installer immediately converts the disk to APFS format before installation begins, right? Isn't that pointless?

**Comment by kholia** [comment]
@thenickdude Oh, I did not know that ;). In that case, I will remove the non-APFS recommendation and go with the flow. Thanks!

**Comment by FlorianHeigl** [comment]
I just started out with APFS and can only boot to recovery. Seems there's a bit more specialties involved.

**Pull request closed without merging**
