### PR TITLE
Pass paths via command-line arguments to create_iso_* scripts

### PR DESCRIPTION
**Pull request by p12tic**
This makes life for people dealing with multiple OSX versions much easier.

### CODE REVIEW

**Comment by kholia** [comment]
Thanks.

Would it be possible to add auto-detection of standard path(s), if no arguments are supplied?

**Comment by p12tic** [comment]
Fixed now.

**Comment by kholia** [comment]
Thanks.

I will test this PR and include it in next batch update.

**Comment by kholia** [comment]
I have merged this change in `Batch update for January, 2019` commit. Thanks!

**Pull request closed without merging**
