### PR TITLE
Ventura board updated in fetcher

### PR DESCRIPTION
**Pull request by scizzydo**
Would pull Sonoma BaseSystem.dmg with the board that was set

### CODE REVIEW

**Comment by pietryszak** [comment]
It's working, thank you :)

**Comment by sanderDijkxhoorn** [comment]
Ventura option is still pulling Sonoma for me

**Comment by cyrilfr** [comment]
> Ventura option is still pulling Sonoma for me

I have the exact same problem, no matter the version of fetch-macOS-v2.py I use...

**Comment by pietryszak** [comment]
> > Ventura option is still pulling Sonoma for me
> 
> I have the exact same problem, no matter the version of fetch-macOS-v2.py I use...

Because is pull request? 
It's not merged with code yet.

fetch-macOS-v2.py change line 532 from Mac-7BA5B2D9E42DDD94 to Mac-4B682C642B45593E and it's working

**Comment by cyrilfr** [comment]
> > > Ventura option is still pulling Sonoma for me
> > 
> > 
> > I have the exact same problem, no matter the version of fetch-macOS-v2.py I use...
> 
> Because is pull request? It's not merged with code yet.
> 
> fetch-macOS-v2.py change line 532 from Mac-7BA5B2D9E42DDD94 to Mac-4B682C642B45593E and it's working

Makes sens. Thanks for your quick reply!

**Comment by sanderDijkxhoorn** [comment]
My bad, didn’t checkout the correct branch I’ll try it again tomorrow. :)

**Comment by pietryszak** [comment]
> My bad, didn’t checkout the correct branch I’ll try it again tomorrow. :)

You don't need change the branch, just use main and change a proper line in fetch-macOS-v2.py before starting a script.

**Comment by pietryszak** [comment]
@kholia it's good idea to merge that change

**Comment by sanderDijkxhoorn** [comment]
With the PR's code it works, thanks!

**Comment by wickloww** [comment]
Hi, it doesn't work for me. I get this message : "An error occurred while preparing the installation. Try running this application again.".
Here are the latest logs I got:
image

**Comment by sanderDijkxhoorn** [comment]
> Hi, it doesn't work for me. I get this message : "An error occurred while preparing the installation. Try running this application again.".
> Here are the latest logs I got:
> image

I am getting the same while running the installer.

**Comment by whosthegoss** [comment]
> > Hi, it doesn't work for me. I get this message : "An error occurred while preparing the installation. Try running this application again.".
> 
> > Here are the latest logs I got:
> 
> > image
> 
> 
> 
> I am getting the same while running the installer. 

I thought I was going crazy. I get this for both Ventura and Sonoma. I spent all day yesterday retrying thinking I was doing something wrong. Glad to see another user report the same.

**Comment by valtbarbos** [comment]
Same problem here, but even with the Ventura the result is the same with Sonoma: "An error occurred while preparing the installation. Try running this application again." -- 12min/18min to finish; I tried repeatedly yesterday with different approaches. People using the docker are getting the same error. There seems to be a problem with the source image, does it make sense?

**Comment by cyrilfr** [comment]
I've the same issue. I think this is simply broken...

**Comment by whosthegoss** [comment]
It's possible Apple added other checks that are not accounted for in EFI. I could get Mojave to install, pull the upgrade DB installer and end up with the same errors.

**Comment by RichardFevrier** [comment]
Maybe we should create another issue to track this problem.

**Comment by pietryszak** [comment]
> Maybe we should create another issue to track this problem.

If it's not connected with pull Sonoma image, then yes.

**Comment by AhirGhosh** [comment]
> > Hi, it doesn't work for me. I get this message : "An error occurred while preparing the installation. Try running this application again.".
> > Here are the latest logs I got:
> > image
> 
> I am getting the same while running the installer.

same error for me as well, even after upgrading qemu

**Comment by AhirGhosh** [comment]
> > > Hi, it doesn't work for me. I get this message : "An error occurred while preparing the installation. Try running this application again.".
> > 
> > 
> > > Here are the latest logs I got:
> > 
> > 
> > > image
> > 
> > 
> > I am getting the same while running the installer.
> 
> I thought I was going crazy. I get this for both Ventura and Sonoma. I spent all day yesterday retrying thinking I was doing something wrong. Glad to see another user report the same.

same error for me as well today after 1 hour , changed the file partition from APFS to Mac-OS Journaled but no joy, even upgrading QEMU did not work

**Comment by netanelc305** [comment]
anyone manage to solve this?

**Pull request merged**
