### PR TITLE
Added boot-usb-passthrough.py

### PR DESCRIPTION
**Pull request by 0Franky**
This script detects when USB is connected and starts macos by performing USB Passthrough.  
**Note:** It also works by connecting different USB devices.  

**How it works:**  
When the program starts, an analysis of all the USB devices that will be connected from that moment until the enter key is pressed to confirm is started.
The program will propose the parameters necessary to perform USB Passthrough to be passed to QEMU.
The program will ask you to start macOS, if you accept, it will read the contents of the `OpenCore-Boot.sh` file and run a fixed script by adding the parameters mentioned above.

### CODE REVIEW

**Comment by sanderDijkxhoorn** [comment]
@lazarscorro and I tried it both with a iPhone but we could not get it to work correctly, when the mac boots the iphone seems to reconnect and I can't use it in macOS

**Comment by 0Franky** [comment]
Unfortunately I don't have an iPhone so I couldn't test it. But reading the notes there is a specific section for binding iPhones. If you can make it work with that and give me additional details I can try to improve the script.

**Comment by sanderDijkxhoorn** [comment]
> @sanderDijkxhoorn Unfortunately I don't have an iPhone so I couldn't test it. But reading the notes there is a specific section for binding iPhones. If you can make it work with that and give me additional details I can try to improve the script. anyway I'll try to connect Android phone.

Hmm I didn't see the notes, I will check it out later thanks :)

**Comment by 0Franky** [comment]
@sanderDijkxhoorn any updates?
I'm working on a GUI application to perform usb-storage/PCI passthrough. 
but I need help. i need to understand better how to perform phone pci passthrough. 

were you able to connect your iPhone to MacOS? if so, can you tell me the steps you took?

**Comment by sanderDijkxhoorn** [comment]
> @sanderDijkxhoorn any updates? I'm working on a GUI application to perform usb-storage/PCI passthrough. but I need help. i need to understand better how to perform phone pci passthrough.
> 
> were you able to connect your iPhone to MacOS? if so, can you tell me the steps you took?

Sorry for the late reply, unfortunately had no time to check it out yet… been trying this out on my work PC but have been sick at home for a week now. (Don’t have a RDP just SSH)

I am not a expert with VMs or device pass trough etc so not sure if I could help you :!

**Comment by kholia** [comment]
I am NOT planning to maintain this in the tree. Thanks for the PR though!

**Pull request closed without merging**
