### PR TITLE
Set XHCI controller to qemu-xhci for USB keyboard/ mouse on macOS 14.4

### PR DESCRIPTION
**Pull request by jprx**
This fixes the USB keyboard/ mouse issues on macOS 14.4. May not work with older versions of macOS, I only tested 14.4.

### CODE REVIEW

**Comment by Berikai** [comment]
Thank you!!! I have been searching for a fix to the mouse option for a while. This is the only solution that has worked.

**Comment by LOASMATRIX** [comment]
Hi, I have exactly the same problem. I changed it in the ./OpenCore-Boot.sh. Unfortunately no effect. Where exactly does this need to be changed? thanks in advance.

**Comment by LOASMATRIX** [comment]
I think I found it, thanks

**Comment by ran000** [comment]
Thanks
I get working my updated Sonoma 14.4.1 by adding some lines to macOS-libvirt-Catalina.xml file (https://github.com/kholia/OSX-KVM/blob/master/macOS-libvirt-Catalina.xml):
    <controller type='usb' index='1' model='qemu-xhci'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
...
    <input type='mouse' bus='usb'>
      <address type='usb' bus='1' port='1'/>
    </input>
    <input type='keyboard' bus='usb'>
      <address type='usb' bus='1' port='2'/>
    </input>

**Comment by ran000** [comment]
Thanks
I get working my updated to 14.4.1 Sonoma by adding some lines to    [macOS-libvirt-Catalina.xml](https://github.com/kholia/OSX-KVM/blob/master/macOS-libvirt-Catalina.xml): 

[t.txt](https://github.com/kholia/OSX-KVM/files/14826962/t.txt)

**Comment by farheinheigt** [comment]
Merci bro !

**Comment by hayderhadexplodedearlier** [comment]
in which file do i need to change this?

**Review by kholia — APPROVED** [review]

**Comment by Rafiburbu** [comment]
Im very begginer at this, when I want to install MacOS Sonoma but the installer did not detect the mouse, then, I found this, but I dont know how to use it

**Comment by wetsand24** [comment]
> Im very begginer at this, when I want to install MacOS Sonoma but the installer did not detect the mouse, then, I found this, but I dont know how to use it

Goto your virtualbox machine settings --> USB -> and use USB 3.0 (xhci controller)

image

**Comment by FlorianHeigl** [comment]
For others like me - if you find you still can't use your mouse at the boot screen - just use the keyboard, proceed and then on the next step the mouse will be avaliable :-)

**Pull request merged**
