### PR TITLE
Default Resolution - 1920x1080

### PR DESCRIPTION
**Pull request by morganlombard**
I made an update to use a default resolution of 1920x1080 for both OVMF_VARS and Clover image

### CODE REVIEW

**Comment by kholia** [comment]
Thank you!

I want the default resolution to be safe and the most widely supported one. It should work on 720p monitors for now.

**Comment by kholia** [comment]
Quick notes:

- The PR has a bunch of changes unrelated to the resolution change.

- I would prefer to retain the existing default safer resolution. However, I would love to see the process of getting higher resolutions well documentated (new PR?).

**Comment by morganlombard** [comment]
I can add the description to the main Readme.md that explains how to get
higher resolution in the Post Installation section

**Comment by kholia** [comment]
@morganlombard I recommend adding these notes in `notes.md` file and then linking to them in `README.md`.

**Comment by kholia** [comment]
I am closing this one.

**Pull request closed without merging**
