### PR TITLE
Get the BaseSystem.dmg with macrecovery.py

### PR DESCRIPTION
**Pull request by Broly1**
Opencore  has an built in script to download the recovery inside /OpenCore-x.x.x-RELEASE /Utilities/macrecovery/
BigSur BaseSystem.dmg is only 2.8GB so makes the download much faster and less stuff to extract, also opencore can boot the BaseSystem.dmg directly on bare metal by creating a folder named ``com.apple.recovery.boot`` and dropping in  the` BaseSystem.dmg` plus the `BaseSystem.chunklist` inside of it on a formated FAT32 drive so It may be possible to boot with KVm as well I belive.
https://github.com/Broly1/OpenCore-Install-Guide/blob/master/installer-guide/linux-install.md

### CODE REVIEW

**Comment by kholia** [comment]
Thanks.

We can't just switch to `macrecovery.py` as it requires extra arguments to run it. It is too big of a change perhaps?

**Comment by kholia** [comment]
Maybe I can build a menu system around this program and call it `fetch-macOS-v2.py`?

**Comment by kholia** [comment]
https://github.com/kholia/OSX-KVM/blob/master/fetch-macOS-v2.py is up now.

Thanks for the idea.

**Comment by Broly1** [comment]
No problem, good job.

**Pull request closed without merging**
