### PR TITLE
Update macOS-libvirt-Catalina.xml

### PR DESCRIPTION
**Pull request by Dogr95**
fixed missing BaseSystem image for installation otherwise wont boot

### CODE REVIEW

**Comment by mikehardy** [comment]
@Dogr95 I have a question for you, if you are using this. I've tried and tried to get this to work via libvirt vs via the qemu command line, and I cannot do so without having some serious timer issues. Like, if you enable FileVault when it boots you have to enter a password and it doesn't seem to be recognizing interrupts as they come, when fully booted there are issues leading to network throughput being low etc. 

Do you also suffer from this, or is it fully working for you?

**Comment by mikkeyboi** [comment]
@mikehardy The change seems to add the created BaseSystem installer so that upon the first boot you can run the installer. Afterwards, you can/should remove those lines because it is no longer necessary to have it mounted.

The issues you described seem to be related to your xml, but not the changes in their PR. Have you tried changing your NIC?

**Comment by mikehardy** [comment]
For the avoidance of doubt: my question is a tangent and I apologize to all participants, I was just curious if anyone had seem timer issues like I had. I believe it is more related to the system clock source (e.g. pit etc) but I'm much too inexperienced to know for sure. I was using the xml straight from the repo with only changes being cpu type (so I could do nested virt) then adding cpus and ram. 🤷 . I'm just using qemu command line direct and it works perfectly. Anyway, I don't want to distract too much from the actual work here so unless you know something off the top of your head no worries. I'm grateful the OSX-KVM stuff works at all, it's a fantastic resource. Cheers

**Comment by kholia** [comment]
This is merged in `Batch Update 1 - January 2021`. Thanks :+1:

**Pull request closed without merging**
