### PR TITLE
Update GPU passthrough notes for macOS Ventura and non-AVX2 CPUs

### PR DESCRIPTION
**Pull request by gary17**
Augment GPU passthrough notes with additional information on patching macOS Ventura to work with hardware GPUs and pre-Haswell (non-AVX2) CPUs.

### CODE REVIEW

**Comment by gary17** [comment]
Sorry, GitHub closed the pull request on renaming the branch.

**Comment by vleeuwenmenno** [comment]
This does not apply for the `boot-macOS-headless.sh` ?

**Comment by escozul** [comment]
Sorry to bother you after so many months. I'm curious if I installed Ventura correctly on my late 2016 Macbook Pro (Identifier: MacbookPro 13.3 with an i7-6920HQ and 460 AMD Polaris with 4Gb Vram).

I seem to be running games okay, (I tried Kerbal Space program and Universe sandbox). And Apple TV using an external monitor on clamshell mode seems to be reworking fine. It did crash a few times but after a couple of restarts, seems to be working. Not sure if it'll last.

I have to test though and not sure how to test. Any ideas? Some software that will give me a report?

Just to note, I tried running No Man's Sky but I got a blank screen with the music running in the background. The FPS counter was working but the game seemed to render only black. That could be the game's fault though since it's supposedly does not work on my hardware. It did not crash though. I was able to quit the game and try something else. Only the screen was dark.

I'd really appreciate any help with this to make sure I've done all the proper configurations to have a working Vetnura. It seems to me that I have no other incompatibilities but I need to be reassured with a couple of tests and maybe make some configuration changes I was unable to? I only ran the setup, installed OCLP and ran the Root Patch. Don't know what else to do to make sure the Dedicated GPU works.

Thank you

**Comment by gary17** [comment]
> I have to test [macOS] though and not sure how to test. Any ideas? Some software that will give me a report?

Since the OpenCore Legacy Patcher (OCLP) customizes the macOS GPU driver stack, OCLP documentation is the only possible source of information on further OCLP configuration, troubleshooting and potential compatibility problems. Other than that, you can always try to run any general-purpose macOS GPU stress test or GPU benchmark software on an OCLP system just to see if the test reports anything out of the ordinary.

**Comment by gary17** [comment]
> I think I missed a step in installing (but can't find which). Could you point me in the right direction? Some Discord channel a forum to take this issue further?

OCLP documentation and OCLP Discord are probably the only possible sources of information regarding a customized OCLP GPU stack. Note that the OCLP Discord community supports macOS on Apple hardware only, they don't help with virtualized or hackintosh macOS.

**Comment by escozul** [comment]
> > I think I missed a step in installing (but can't find which). Could you point me in the right direction? Some Discord channel a forum to take this issue further?
> 
> OCLP documentation and OCLP Discord are probably the only possible sources of information regarding a customized OCLP GPU stack. Note that the OCLP Discord community supports macOS on Apple hardware only, they don't help with virtualized or hackintosh macOS.

Yes, no problem. I was referring to my MacBook pro 13.3 (2016). I'm not on a hackintosh.
looking for the Discord Community now. Didn't see it when I started installing.

**Comment by dav1dxyz** [comment]
Is it possible to use an offline installer and still use this method with vmware-svga? I've been trying to get Sonoma working with ivy bridge, and I would prefer to use the offline installer as my internet isn't the fastest.
I have tried installing Ventura with recovery, and I had the same issue as Docker-OSX:511

**Comment by gary17** [comment]
> Is it possible to use an offline installer and still use this method with vmware-svga?

If I remember correctly, I used to successfully install older macOS versions from scratch using the offline installer under QEMU with `-device vmware-svga`. I don't know about Sonoma or Docker. There is no way to configure QEMU to emulate only the AVX2 CPU instruction in software and execute all other CPU instructions in hardware (directly on a host CPU).

**Comment by kholia** [comment]
I will update the GPU passthrough notes in the repository soon.

**Pull request closed without merging**
