### PR TITLE
Cleanup and simplifying things

### PR DESCRIPTION
**Pull request by felfert**
Hi,

This pull request does a major cleanup and simplifies iso creation.

* The custom boot plist is added in the iso.
Therefore, typing the boot options manually in the console is **not** required anymore.
* The kernel is automatically extracted. No need for manually fiddling around with closed-source tool (Pacifist)
* The postinstall method of adding the custom boot plist is replaced by a simpler method inside the booted VM.

### CODE REVIEW

**Comment by kholia** [comment]
Thanks for the awesome pull request @felfert :+1: 

Can you please squash the commits into one to keep the commit history cleaner?

It would be great to commit the new screenshots to the repository itself (in the "screenshots") folder.

Rest of the stuff looks great.

**Comment by felfert** [comment]
On 14.08.2016 08:24, Dhiru Kholia wrote:
> Thanks for the awesome pull request @felfert
> <https://github.com/felfert> 👍
> 
> Can you please squash the commits into one to keep the commit history
> cleaner?

Nope. I have made multiple changes which are all worth mentioning. Apart
from that, my branch is already pushed and merged elsewhere. Doing a
rebase at this state whould make a big mess. Feel free to squash the
commits in your master after merging my PR.

> 
> It would be great to commit the new screenshots to the repository itself
> (in the "screenshots") folder.

Well, that would contradict my PR.
My PR *removes* the whole screenshot folder in favor of this approach:
http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

Cheers
 -Fritz

**Comment by njaremko** [comment]
So you want to commit > 3x the current amount of commits, despite most of your commits amounting to "Fixed a typo"? 

I mean, I'm personally against the whole "squash before merge" trend, but you could at least squash most of them into a few well described commits...

Furthermore, the fact that you "pushed and merged elsewhere" is irrelevant. Making the changes, deleting your other repo, and republishing it should be trivial.

**Comment by kholia** [comment]
I have pulled in the changes manually, thanks :+1:

**Pull request closed without merging**
