### PR TITLE
Notes on vmxnet3 adapter

### PR DESCRIPTION
**Pull request by CuriousTommy**
Hello kholia,

The current pull request is currently not ready to be merged, but I thought I would submit a pull request so that you can give feedback on my edits. I am not sure how I should word/organize the information. 

The network document file never talks about `vmxnet3`, despite it being mentioned [in one of the scripts](https://github.com/kholia/OSX-KVM/blob/master/boot-macOS.sh#L15). Being inspired by pickled_monkey's Reddit comment on vmxnet3, I thought it would be a good idea to bring awareness to the alternative adapter.

Once it is ready to merge, I can squash my commits. Let me know what you think!

(Personal) Notes: 
[VMXNET3 Driver included in El Capitan](https://www.virtuallyghetto.com/2016/10/vmxnet3-driver-now-included-in-mac-os-x-10-11-el-capitan.html)
[pickled_monkey's notes on vmxnet3](https://www.reddit.com/r/hackintosh/comments/7q8yxh/high_sierra_inside_linux_with_pci_passthrough/dst5raj/)

### CODE REVIEW

**Comment by kholia** [comment]
I will pull this in in the next batch update.

**Comment by kholia** [comment]
These changes have been pulled in now.

**Comment by kholia** [comment]
Ack.

I have now added the following line to the CREDITS file,

```
CuriousTommy + pickled_monkey - Information on vmxnet3 network adapter
```

**Comment by CuriousTommy** [comment]
Perfect, thanks!

**Pull request closed without merging**
