### PR TITLE
Support for macOS moniker

### PR DESCRIPTION
**Pull request by RobertDeRose**
Supports finding Installer applicationf for OS X and now macOS.

Also got rid of the need of the `sed` command to strip out the final `/`

### CODE REVIEW

**Comment by kholia** [comment]
I have manually pulled in this change. Thanks :+1:

**Comment by hobarrera** [comment]
@kholia Is there any specific reason to re-write the repository history and attribute the changes to yourself? Not only does this hide actual authorship, it also makes pulling the repo a pain due to git history rewrites.

**Comment by kholia** [comment]
There were various Apple owned binary blobs in this repository initially. I had to rewrite history to get rid of them. Then some pull request were weird and I had to merge them manually.

Also, I have a OCD about keeping the project history clean. I update the "Credits" section in README.md to give credit where it is due.

**Comment by RobertDeRose** [comment]
@kholia thanks for adding me to the credits, that's cool!

**Comment by hobarrera** [comment]
> Also, I have a OCD about keeping the project history clean.

But the history isn't clean at all; it's been erased.

It's impossible for anyone to know what's changed, why certain changes are done, or what fixes a specific issue. I really don't see the need for such opaque development workflow.

**Comment by kholia** [comment]
Sorry but it is what it is for now. Take it or leave it.

**Pull request closed without merging**
