### PR TITLE
Added instructions to use the VM in gnome boxes

### PR DESCRIPTION
**Pull request by tallero**
As the title says.

### CODE REVIEW

**Comment by kholia** [comment]
Thanks!

I don't use `GNOME Boxes` and wouldn't be able to test and maintain support for it. Maintaining support for `virt-manager` (which I also don't use) is proving to be painful enough.

**Comment by kholia** [comment]
I am closing this for now. We may (or may not) revisit this in the future.

**Comment by kholia** [comment]
https://blog.agchapman.com/configuring-gnome-boxes-vms-using-virt-manager/. It seems `gnome-boxes` is pretty limited (for simplicity?) and will be a sort of a dead-end when users want to customize/tweak their virtual machines further (e.g. expose GPUs/ SSDs)?

**Comment by tallero** [comment]
Yup. The main advantage in this setup is that it is easy to toggle fullscreen and switch input context.

On supported images, it syncs vm and window resolution and support many features out of the box.
I noticed the same does not happen on virt-manager so that's the main reason I use it. Of course the latter exposes many more options.

**Pull request closed without merging**
