### PR TITLE
Fix libvirt crash on macOS Ventura

### PR DESCRIPTION
**Pull request by adipascu**
This brings the display setting to be the same as the recent changes done to the [boot-macOS-headless.sh](https://github.com/kholia/OSX-KVM/commit/bd762570abda8498e67f128fbf675f5858f8d51e#diff-da98d65a03457fcbd5baf52bc63b9ac507f03a740f28a0a006ae40cb775aa5f6R66) file.

### CODE REVIEW

**Comment by mid-kid** [comment]
Works like a charm!

**Comment by YuruiHong** [comment]
Still doesn't work for me. Any further modifications or changes in workflow?🥺

**Comment by jdholtz** [comment]
This worked for me as well. Thanks!

**Comment by jdholtz** [comment]
@victorYghor this fixed the installer halting at a certain point for me, but I still ended up getting  “An error occurred during installation” message while running the installer. So it still isn’t fully fixed for me, but this configuration helps me at least the installer. 

I’m running Arch Linux on x86_64 with an intel CPU.

**Comment by Jed0345** [comment]
I'm getting this error after trying to update macOS Montrery to Ventura. Anyone know how to fix that?

"Couldn't alloc class "applekeystoretest". 

My specs are, rx580, Ryzen 5 2600, On Linux Mint > running qemu virt-manager 

the first cli method wasn't working for me, but I managed to install montrery after switching to virt-manager

**Comment by Burtan** [comment]
> I'm getting this error after trying to update macOS Montrery to Ventura. Anyone know how to fix that?
> 
> "Couldn't alloc class "applekeystoretest".
> 
> My specs are, rx580, Ryzen 5 2600, On Linux Mint > running qemu virt-manager
> 
> the first cli method wasn't working for me, but I managed to install montrery after switching to virt-manager

I'm getting the same crash. Ryzen 2700x, Debian 12

**Comment by Jed0345** [comment]
> > I'm getting this error after trying to update macOS Montrery to Ventura. Anyone know how to fix that?
> > "Couldn't alloc class "applekeystoretest".
> > My specs are, rx580, Ryzen 5 2600, On Linux Mint > running qemu virt-manager
> > the first cli method wasn't working for me, but I managed to install montrery after switching to virt-manager
> 
> I'm getting the same crash. Ryzen 2700x, Debian 12

I managed to fix it actually. There are appears to have been an issue with the type of display you have set. So try messing around with those settings. I think I just changed mine to virtio and it fixed the issue.

**Comment by kholia** [comment]
This PR was merged manually - thanks!

**Pull request closed without merging**
