### PR TITLE
arch install instructions

### PR DESCRIPTION
**Pull request by lollilol**
add arch install instructions

### CODE REVIEW

**Review by keinsell — COMMENTED** [review]
+1, Not neecessary but helpful at some point

**Comment by mrsafalpiya** [comment]
+1

**Review by JacktheDevel0per — COMMENTED** [review]
dmg2img is now in the aur, so it should be put at the end after invoking paru

**Comment by kholia** [comment]
Only Ubuntu is officially supported and tested.

**Pull request closed without merging**
