### PR TITLE
UNRAID Documentation and Examples

### PR DESCRIPTION
**Pull request by mikkeyboi**
As mentioned from #159 this PR adds UNRAID documentation: to show how this repository can be used to make VMs in UNRAID KVM. If there are any changes you'd like to make, please let me know - I will commit, no files should conflict between the base/head.

When the PR is ready, please merge (as more contributes to the documentation it'll be helpful for version controlling and git blame tracking).

Below is a sample of the documentation (so you don't have to preview from my fork).

# Setting up OSX-KVM with UNRAID
Note: SpaceInvaderOne has a community app called "macinabox", and it is a Docker container that can automate the entire process that creates the VM and disks. This guide aims to provide utility in choosing specific macOS versions or bootloaders, and understanding the process of how this repository's resources can be used in hypervisor types (UNRAID, ESXi, etc.).

- [Setting up OSX-KVM with UNRAID](#setting-up-osx-kvm-with-unraid)
  - [Motivation](#motivation)
  - [Pre-Requisites](#pre-requisites)
  - [Preparing the VM](#preparing-the-vm)
  - [Starting the VM](#starting-the-vm)
  - [Optional Notes](#optional-notes)
  - [Misc](#misc)
  - [Resources](#resources)

## Motivation
This guide solely uses the files generated from this repository to construct a VM for use in UNRAID. This means updates to and features of this repository should be compatible with creating VMs in UNRAID. This type of setup also aims to utilize UNRAID's advantages to address items in the [Contributing Back](https://github.com/kholia/OSX-KVM#contributing-back) section of the main repository, including creating/re-using VM snapshots, build farms, VNC+SSH support, and capacity of delivering a bare-metal-like experience for development. Further customization in setting up Hackintosh on KVM is beyond the scope of this documentation, but feel free to provide relevant [supplemental resources](#resources).

## Pre-Requisites
Follow the [Installation Preparation](https://github.com/kholia/OSX-KVM#installation-preparation) guide and have your disk image `mac_hdd_ng.img` and installation media `BaseSystem.dmg` ready. 

Ensure you have VM support and passthrough parameters prepared (VFIO devices, PCI controllers, VNC remote, etc.). You should also have a way of reading/writing to the appropriate locations in your UNRAID server (I use Krusader).

## Preparing the VM
Below are sample instructions for setting up the VM. We will keep the necessary files in the same directory for simplicity.
* Place these 3 files `BaseSystem.img`, `mac_hdd_ng.img` and `OSX-KVM/OpenCore-Catalina/OpenCore.qcow2` into the directory of your VM
  * ie: Into `/mnt/user/domains/BigSur`, where domains is the folder for your VMs
* Create a new VM and edit the XML. Use the OSX-KVM repository's `macOS-libvirt-Catalina.xml` as a guide
  * ie: You also have the option to use the GUI to adjust the CPUs, RAM, setting the OS installation media and disk images, as well as the devices you wish to pass into the VM. However, each time the template is edited via the GUI, you must go in the XML editor and paste the qemu args at the bottom of the XML file.
  * Note: The opencore qcow2 file should be prioritized first, it will contain the EFI boot partition that you can modify after installation using the OpenCore Configurator
* Check that the three files' primary vDisk bus is SATA, and verify types:
  * OpenCore.qcow2 `<driver name='qemu' type='qcow2' cache='writeback'/>`
  * BaseSystem.img `<driver name='qemu' type='raw' cache='writeback'/>`
  * mac_hdd_ng.img `<driver name='qemu' type='qcow2' cache='writeback'/>`
* After successful installation, the BaseSystem.img entry can be safely deleted from the XML

## Starting the VM
* Initialize the VM, and select the macOS base system when OpenCore prompts
* Once the installer boots, go into disk utility and erase the qemu drive that relatively matches the space you've allocated in the qemu-img args
  * ie: Erase the disk and use these params - APFS, GUID Partition Table
* After installation, you may need to change the NIC to `vmxnet3` or `e1000-82545em` to login with your Apple ID or install your apps from the AppStore (consult [Resources](#resources) for other network interface types)
* Download OpenCore Configurator and mount the EFI partition called `EFI o` (Tools > Mount EFI) 
OpenCore EFI Partitions
* Open the plist from Tools > Scan Configurations
OpenCore plist

* Customize aml/kext/nvram/drivers and save
  * Note: Making modifications here will write to the `OpenCore.qcow2` file copied from this repository.

## Optional Notes
In no particular order, 
* For the RX 5700XT, the boot-args `agdpmod=pikera` is necessary to successfully boot. Change in `NVRAM > UUID > boot-args (right-click) > WhateverGreen > agdpmod=pikera` 
  * Use VNC or another GPU until able to configure the EFI partition, or pre-configure the qcow2 file
* Simplify updates by creating another VM template that does not passthrough the GPU (noVNC)
  * During OS updates, multiple restarts occur. If you use an AMD GPU that has the reset-bug, this process can be jarring
  * Each restart there will be another boot option alongside your default one (from the update), choose that one until the update is complete
* For passing PCIe USB controllers. ensure they work with macOS and ensure its free by vfio-bind them on server boot

When there is a home for this section, feel free to share optimizations and configurations that require modifications to the qemu args, XML, config plist, etc. 

## Misc

qemu args
```
  <qemu:commandline>
    <qemu:arg value='-usb'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='usb-kbd,bus=usb-bus.0'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc'/>
    <qemu:arg value='-smbios'/>
    <qemu:arg value='type=2'/>
    <qemu:arg value='-cpu'/>
    <qemu:arg value='Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check'/>
  </qemu:commandline>
```

## Resources

* [https://forums.unraid.net/topic/84430-hackintosh-tips-to-make-a-bare-metal-macos/](https://forums.unraid.net/topic/84430-hackintosh-tips-to-make-a-bare-metal-macos/)
* [SpaceInvaderOne: How to Easily Install macOS Catalina Mojave or HighSierra as a VM on Unraid](https://www.youtube.com/watch?v=g_jk9D2e5q0)
* [Macinabox GitHub Repository](https://github.com/SpaceinvaderOne/Macinabox)

### CODE REVIEW

**Comment by AdamMomen** [comment]
@mikkeyboi this is really amazing! I got my hopes back agian. How is the performance looks like after gpu acceleration?

Could it be used on wsl2?

**Comment by mikkeyboi** [comment]
> @mikkeyboi this is really amazing! I got my hopes back agian. How is the performance looks like after gpu acceleration? 

Glad to hear! Performance while dedicating 2 CPUs on my Ryzen 5 3600 and 16GB of RAM felt as snappy as my MacBook Pro 15" i7 2018, doing some simple tasks on XCode. This was all concurrent with my Windows VM that's running its own workloads while sharing one common CPU core.

> Could it be used on wsl2?

Do you mean whether you can use WSL2 on a Windows 10 VM created by UNRAID? Yes, while I have the above workload running I also have Ubuntu on WSL2. Nested virtualization / Hyper-V is supported, and I haven't experienced any slowdowns while using both the Windows and macOS VMs.

**Comment by sickcodes** [comment]
Can you confirm this only works for external cards rather than iGPUs on AMD laptops? Very interested!

**Comment by mikkeyboi** [comment]
> Can you confirm this only works for external cards rather than iGPUs on AMD laptops? Very interested!

I do not have an AMD laptop to test, but AFAIK integrated GPUs (APUs) on the Ryzen chips (ie: 3200G) cannot passthrough into a VM in UNRAID. However, there are people reporting [successful passthroughs of certain generations of Intel IGDs (Integrated Graphics Device)](https://forums.unraid.net/topic/45385-intel-igd-integrated-graphics-pass-through-support-march-2016-update/).
I cannot confirm if "this only works for external cards" as in eGPUs (type-C/thunderbolt 3 enclosures), but it should if you passthrough the type-C bus into the VM. 

So if you have UNRAID set up you should be able to use resources in this repository to create and simultaneously run as many macOS VM's as you like. For example, on an [i7-8700](https://forums.unraid.net/topic/45385-intel-igd-integrated-graphics-pass-through-support-march-2016-update/?do=findComment&comment=794722), RTX 2080, RX 5700XT running 3 macOS and 1 Linux:
1. Ubuntu VM w/ RTX 2080 Passthrough (daily-driver monitor 1), QEMU macOS VM Big Sur nested
1. macOS Big Sur VM w/ RX 5700XT Passthrough (daily-driver monitor 2)
1. macOS Big Sur VM headless w/ Intel IGD Passthrough (daily-driver monitor 3)

@kholia this setup above would be a sample schematic of a [build farm (contributing back)](https://github.com/kholia/OSX-KVM#contributing-back), with two GPU-accelerated macOS VM's and 1 macOS VM running from your qemu script. Or it could be 3 sets of monitors and keyboards/mice for a team project (Type-C USB passthrough / PCIe USB passthrough / motherboard USB controller passthrough). If you want me to add more details I can commit in this fork.

**Comment by mikkeyboi** [comment]
@kholia If there are no concerns can you merge so that this PR does not become stale? There are no conflicts, and I'll maintain the links it has to the main documentation if the main docs change.

**Comment by kholia** [comment]
@mikkeyboi Hey! I am working on this today :)

It will likely be merged in the next 2-3 hours or so.

**Comment by kholia** [comment]
https://github.com/kholia/OSX-KVM/blob/master/UNRAID.md is live now! Thanks.

I merged this PR manually to remove some whitespace stuff and to add you to the `CREDITS.md` file.

**Comment by mikkeyboi** [comment]
Thank you, I was hoping you'd use the git merge so in future contributions I can use `git blame` for tracking when and who inserted the lines, as an additional layer of version control.

**Pull request closed without merging**
