### PR TITLE
Make opencore installer english

### PR DESCRIPTION
**Pull request by foxtrotdragon**
I am unsure what causes it, but open core refuses to open language chooser and instead defaults to chinese this just forces english

### CODE REVIEW

**Comment by kholia** [comment]
Thanks - will test and merge in the next update.

**Comment by Multipixelone** [comment]
This file didn't help. Still uses Chinese for me.

**Comment by crazyquark** [comment]
Did not help me either, still Chinese :)

**Comment by foxtrotdragon** [comment]
You will need to remake the opencore image or what I would do and did mount it, and edit the plist in the image to match this.

**Comment by d0zme** [comment]
To change the Recovery language, choose the third option (starting from the left) of the menu bar, and choose the first option. This will allow you to change its language

**Comment by foxtrotdragon** [comment]
For me this didnt work, I would get a terminal pop up and said something along the lines of no languages? I can't quite remember but I sanity checked on another computer and using the non opencore,

**Comment by NaruFGT** [comment]
I gave these edits a try using guestfish and it does not fix the issue for me, however d0zme's recommendation did work. I also tried rebuilding the OpenCore qcow image but the resulting image was not bootable. I'm confused about why the OpenCore image in the repository isn't reproducible for me. @foxtrotdragon is this why you edited the image rather than using `rm -f CloverNG.qcow2 ;` `rm -f OpenCore.qcow2 ;` `sudo ./clover-image-ng.sh  --cfg config.plist --img OpenCore.qcow2` ?
If I'm not the only one having a problem using the script provided it would be helpful for others to document their woes.

**Pull request merged**
